### ISSUE TITLE
中文对不齐

### ISSUE THREAD

**Issue by lancerXXXX** [fcrespo82/vscode-markdown-table-formatter#21]
希望支持一下中文,有中文和英文就对不齐

**Comment by fcrespo82** [comment]
What is the problem? Please add an example.

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/75553768-02ecc900-5a74-11ea-97a0-679dbe675fe2.png)
If there is any Chinese, the table will not match

**Comment by fcrespo82** [comment]
As per microsoft/vscode#72743 this have to do with the font that you are using. 

In that issue is says that Inconsolata (https://github.com/googlefonts/Inconsolata/releases/download/v3.000/Inconsolata-VF.ttf) renders it correctly, I tried and it worked. 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/462171/75585372-b17f1280-5a50-11ea-9f1c-0fd8a2b238ce.png">


I know this is not optimal, but it seams that I can't fix it. It boils down to the specificities of fonts.

**Comment by lancerXXXX** [comment]
Thank you
