### ISSUE TITLE
doesn't handle some emojis

### ISSUE THREAD

**Issue by natestemen** [fcrespo82/vscode-markdown-table-formatter#22]
As an example the following snippet is not changed.
```
| a   | b |
|-----|---|
| one | ❌ |
```
but most other emojis I've test do work.

**Comment by fcrespo82** [comment]
This is another one like #21 and I don't know if I can fix it.

Emojis are multiple length characters that render as "one" unique graphic (the emoji). Since it is not a font it cannot conform to the space that a letter uses, causing this sort of problem.

There is a good explanation about it [here](https://blog.jonnew.com/posts/poo-dot-length-equals-two).

You can see in this image that even the face emoji with most correct size will add up if a lot is used.
<img width="511" alt="image" src="https://user-images.githubusercontent.com/462171/75634755-25efb800-5bef-11ea-9bb0-c87c365d3a7d.png">

I don't know how to address this issue at the moment.

**Comment by natestemen** [comment]
Right, well thanks for taking a look, and if the other issue covers this one then feel free to close it. Still very much appreciate the tool nonetheless!
