### ISSUE TITLE
Exception: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ahorn42** [fcrespo82/vscode-markdown-table-formatter#24]
Hi,

at first thanks for that great extension - it is very useful and safes a lot time :)

Unfortunately since the last vscode update to version 1.43.2 I am getting a `Cannot read property 'trim' of undefined` exception when trying to format some documents - this does not happen on all documents. With your extension disabled I don't get this error. If you tell me how I can provide you more information for debugging this please tell me what you need ;-)

Would be very nice to get that fixed :)

Best regards!

**Comment by ahorn42** [comment]
I can trigger it with the following input

```markdown
| a | a | a | a |
|-|-|
| bb | bb |
```

IIRC this worked some version ago - but may this is only thinking of wishes :D

**Comment by fcrespo82** [comment]
@ahorn42 I’ll look into it when I have some free time. Maybe tonight.

**Comment by fcrespo82** [comment]
On this particular case the table is not properly structured since the header has four columns and the alignment and body has only two. If you paste this table on GitHub it won't format as well.

I guess I could add a little more descriptive message, but I don't see how this is a table that the extension should format. 

If you can show me how this is an important feature I could try to add a configuration like: "Allow empty columns", in that case the last two columns would be empty and the table would format as.

| a | a | a | a |
|-|-|-|-|
| bb | bb |||

**Comment by ahorn42** [comment]
thanks for your reply and having a look at it! - and yes, a more descriptive error message would be nice - this sound more like something went critically wrong ;-)

I am not sure, but I think a least something like
```
| a | a | a | a |
|-|-|-|-|
| bb | bb |
```
was expanded automatically in the past? - But I would really enjoy this feature. But I am not sure what would be better, to have look at the header row or at the headerrow and the row after. Because if only looking at the header row you might also catch some `|`-separeted strings and format them as a table :D
Or maybe trigger on something like:
```
| a | a | a | a |
|-|
```
to automatically prepare a table with four columns?

**Comment by fcrespo82** [comment]
Added some better erro message on 2.0.4 but I'll leave this open to track any improvement or implementation of that feature.
