### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by mundus08** [fcrespo82/vscode-markdown-table-formatter#30]
I have problems installing the extenseion in VS-Core 2020-07.23.
I don't get the "Enable" entry in the command palette.
When trying to format I get:
notificationsAlerts.ts:40 Command 'Markdown Table Formatter: Sort table by header' resulted in an error (command 'markdown-table-formatter.sortTable' not found)

**Comment by fcrespo82** [comment]
Hi, Thanks for reporting this.

I found a couple of bugs related to what you reported and I will fix them asap.

But, for clarification, the command **Markdown Table Formatter: Sort table by header** shouldn't be available at the command palette since it needs some parameters to work correctly. This command is run from the CodeLens above the header as show at the image below.
<img width="290" alt="image" src="https://user-images.githubusercontent.com/462171/89123663-58a42200-d4a7-11ea-8950-88d8e78aecce.png">

So in the next version this command will not be available on the command palette.

**Comment by mundus08** [comment]
Hi,
thanks for your support!
I see 4 entries in the command palette:
![image](https://user-images.githubusercontent.com/13498637/89127206-22d55c80-d4ec-11ea-93bf-d797a7ade5cb.png)
With Shift+Alt+E I get:
![image](https://user-images.githubusercontent.com/13498637/89127268-7fd11280-d4ec-11ea-806d-c686860c08b0.png)

**Comment by fcrespo82** [comment]
Yep, found that bug too. Will release a patch as soon as possible.

**Comment by fcrespo82** [comment]
v2.1.1 published

Should fix these bugs you are seeing.
